### ISSUE TITLE
Decorator for classes

### ISSUE THREAD

**Issue by bazylhorsey** [team23/pydantic-partial#6]
A simple syntax decorator like this would vastly improve this library with how such features are moving towards in modern Python ecosystems.

```python3
import pydantic
from uuid import UUID
from pydantic_partial import optional

class Something(pydantic.BaseModel):
    name: str
    age: int

# All these fields are optional
@optional
class SomethingOptional(Something):
    pass


class SomethingId(Something):
    id: UUID

```

If someone can show me a direction on how to do this, I'm happy to support this ticket.

**Comment by ddanier** [comment]
You could just use:

```python
class SomethingOptional(
    create_partial_model(Something),
):
    pass
```

...which would give you even more control. Does this solve the issue for you?

**Comment by bazylhorsey** [comment]
Hmm, more control perhaps.
But I think the syntactic sugar is a really nice feature for a generalized partial. IMO it is much more readable as a decorator.

**Comment by ddanier** [comment]
I did think about this again when doing my updates to support pydantic v2. My conclusion ist, that I don't really see any benefit in using decorators. In contrast I think this will create some strange use cases.

For example this would be valid:
```python
@optional
class Something(pydantic.BaseModel):
    name: str
    age: int
```

Which would lead to the question why it was not defined as this in the first place:
```python
class Something(pydantic.BaseModel):
    name: str | None = None
    age: int | None = None
```

I know the use case above was going to only use `@optional` on child classes, still you could do something like this:
```python
@optional
class SomethingOptional(Something):
    additional_field: str
```

...which would lead to `additional_field` also being `additional_field: str | None = None` while the code you wrote kind of looks otherwise.

Also having a decorator would actually mean to create a new class from `SomethingOptional`, make all fields optional and then give the new class the name `SomethingOptional` again. I don't really like it being done this way.

So... I will not support creating partial models using a decorator. You may still just implement this yourself, shouldn't be that hard to do. 😉
